# frozen_string_literal: true

require "rubygems"

module Kettle
  module Rb
    module GemFloors
      # Regenerates +lib/kettle/rb/gem_floors/data.rb+ for tracked gems from the
      # rubygems.org versions API and ruby-advisory-db (through bundler-audit).
      #
      # This is development tooling. It is loaded by the
      # +kettle:rb:gem_floors:generate+ rake task, never by +require "kettle/rb"+.
      #
      # For each minor series of a tracked gem the floor is the newest released
      # patch that does not raise the series' original minimum Ruby. When that
      # patch is affected by an advisory but an older compatible patch is not,
      # the newest unaffected patch is used instead. Advisories that still affect
      # the chosen floor are recorded as unpatched.
      class Generator
        # Tracked gems and the oldest minor series to record for each.
        TRACKED = [
          ["activemodel", "5.2"],
          ["activerecord", "5.2"],
          ["activesupport", "5.2"],
          ["sqlite3", "1.3"]
        ].freeze

        DATA_PATH = File.expand_path(File.join(File.dirname(__FILE__), "data.rb"))

        VERSIONS_URL = "https://rubygems.org/api/v1/versions/%s.json"

        # @return [Array<Array(String, String)>] tracked gem names and oldest series
        attr_reader :tracked

        # @return [String, nil] ruby-advisory-db commit recorded in the data file
        attr_reader :advisory_db_commit

        # @return [String] generation date recorded in the data file
        attr_reader :generated_on

        # @param options [Hash]
        # @option options [Array<Array(String, String)>] :tracked gem names and oldest series
        # @option options [#call] :versions_fetcher returns rubygems.org version hashes for a gem name
        # @option options [#call] :advisories_fetcher returns advisories (+#id+, +#vulnerable?+) for a gem name
        # @option options [String, nil] :advisory_db_commit ruby-advisory-db commit to record
        # @option options [String] :generated_on date to record
        def initialize(options = {})
          @tracked = options[:tracked] || TRACKED
          @versions_fetcher = options[:versions_fetcher] || method(:fetch_versions)
          @advisories_fetcher = options[:advisories_fetcher] || method(:fetch_advisories)
          @advisory_db_commit = options.key?(:advisory_db_commit) ? options[:advisory_db_commit] : database_commit
          @generated_on = options[:generated_on] || Time.now.utc.strftime("%Y-%m-%d")
        end

        # @return [Array<Array>] rows for +GemFloors::ROWS+
        def rows
          result = []
          tracked.each do |gem_name, oldest_series|
            result.concat(rows_for(gem_name, Gem::Version.new(oldest_series)))
          end
          result
        end

        # @return [String] Ruby source for +data.rb+
        def render
          lines = [
            "# frozen_string_literal: true",
            "",
            "# Generated by `rake kettle:rb:gem_floors:generate`; do not edit by hand.",
            "# Sources: rubygems.org versions API and ruby-advisory-db.",
            "",
            "module Kettle",
            "  module Rb",
            "    module GemFloors",
            "      GENERATED_ON = #{generated_on.inspect}",
            "      ADVISORY_DB_COMMIT = #{advisory_db_commit.inspect}",
            "      TRACKED_GEMS = #{tracked.map { |pair| pair.first }.inspect}.freeze",
            "      ROWS = ["
          ]
          lines << rows.map { |row| "        #{row.inspect}" }.join(",\n")
          lines.concat(["      ].freeze", "    end", "  end", "end", ""])
          lines.join("\n")
        end

        # Writes the rendered data file.
        #
        # @param path [String]
        # @return [String] the written path
        def write(path = DATA_PATH)
          File.open(path, "w") { |file| file.write(render) }
          path
        end

        private

        def rows_for(gem_name, oldest_series)
          advisories = @advisories_fetcher.call(gem_name)
          by_series = releases_by_series(gem_name)
          result = []
          by_series.keys.sort_by { |series| Gem::Version.new(series) }.each do |series|
            next if Gem::Version.new(series) < oldest_series

            releases = by_series[series].sort_by { |release| release[:version] }
            floor = floor_release(releases, advisories)
            affecting = advisories.select do |advisory|
              releases.any? { |release| advisory.vulnerable?(release[:version]) }
            end
            unpatched = affecting.select { |advisory| advisory.vulnerable?(floor[:version]) }
            result << [
              gem_name,
              series,
              floor[:number],
              floor[:ruby],
              advisory_ids(affecting - unpatched),
              advisory_ids(unpatched)
            ]
          end
          result
        end

        def floor_release(releases, advisories)
          original_ruby = minimum_ruby(releases.first[:ruby])
          compatible = releases.select { |release| minimum_ruby(release[:ruby]) <= original_ruby }
          unaffected = compatible.reject do |release|
            advisories.any? { |advisory| advisory.vulnerable?(release[:version]) }
          end
          unaffected.last || compatible.last
        end

        def releases_by_series(gem_name)
          by_series = {}
          @versions_fetcher.call(gem_name).each do |data|
            next if data["prerelease"]
            next if data["platform"] && data["platform"] != "ruby"

            version = Gem::Version.new(data["number"].to_s)
            segments = version.segments
            next if segments.size < 2

            series = "#{segments[0]}.#{segments[1]}"
            (by_series[series] ||= []) << {:number => data["number"].to_s, :version => version, :ruby => data["ruby_version"]}
          end
          by_series
        end

        def minimum_ruby(requirement)
          floor = Gem::Version.new("0")
          return floor if requirement.nil? || requirement.to_s.strip.empty?

          Gem::Requirement.new(*requirement.to_s.split(/\s*,\s*/)).requirements.each do |operator, version|
            floor = version if [">=", ">", "~>", "="].include?(operator) && version > floor
          end
          floor
        rescue ArgumentError
          Gem::Version.new("0")
        end

        def advisory_ids(advisories)
          advisories.map { |advisory| advisory.id.to_s }.uniq.sort
        end

        def fetch_versions(gem_name)
          require "json"
          require "net/http"
          require "uri"

          JSON.parse(Net::HTTP.get(URI.parse(format(VERSIONS_URL, gem_name))))
        end

        def fetch_advisories(gem_name)
          database.advisories_for(gem_name)
        end

        def database
          require "bundler/audit/database"
          @database ||= Bundler::Audit::Database.new
        end

        def database_commit
          commit = database.commit_id
          commit && commit[0, 12]
        end
      end
    end
  end
end
